Restore enum-compatible methods on `JavaFormatterOptions.Style`
`Style` was changed from an enum to a record, which removed the implicit enum methods. Tools such as Spotless call `Style.valueOf(String)` to map user configuration to a style, and fail with `NoSuchMethodError` against the new version.

- Refs https://github.com/google/google-java-format/pull/1465#discussion_r4173100468
- Closes https://github.com/diffplug/spotless/issues/3126.

Fixes https://github.com/google/google-java-format/pull/1472

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/google/google-java-format/pull/1472 from Goooler:style-enum-compat ab11ed6a272f5383394f7721428281dd9ddbc9e1
PiperOrigin-RevId: 996054769